# Generated by Django 3.2.9 on 2021-11-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=256, verbose_name='Make / Manufacturer')),
                ('part_number', models.CharField(max_length=256, verbose_name='Part / Catalog Number')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IOList.device')),
                ('slot', models.IntegerField()),
                ('address_template', models.CharField(blank=True, max_length=256, null=True)),
            ],
            bases=('IOList.device',),
        ),
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IOList.device')),
                ('name', models.CharField(max_length=26)),
                ('address', models.CharField(max_length=20)),
            ],
            bases=('IOList.device',),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=100, verbose_name='Short Name')),
                ('street', models.CharField(blank=True, max_length=140, null=True, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=140, null=True, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Zip Code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.customer')),
            ],
            options={
                'unique_together': {('customer', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='IOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=82, verbose_name='Controller / IO List Name')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.plant')),
            ],
        ),
        migrations.CreateModel(
            name='ValveBank',
            fields=[
                ('chassis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IOList.chassis')),
                ('data_format', models.IntegerField(choices=[(4, 'SINT DATA'), (8, 'DINT_DATA')])),
                ('valve_count', models.IntegerField()),
            ],
            bases=('IOList.chassis',),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('DI', 'Discrete Input'), ('DO', 'Discrete Output'), ('AI', 'Analog Input'), ('AO', 'Analog Output'), ('RTD', 'RTD Input'), ('TC', 'Thermocouple, Input'), ('HSC', 'High Speed Count Input')], max_length=6)),
                ('tag', models.CharField(max_length=26)),
                ('description_1', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 1')),
                ('description_2', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 2')),
                ('description_3', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 3')),
                ('description_4', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 4')),
                ('user_address', models.CharField(blank=True, max_length=82, null=True, verbose_name='User Specified Address')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.card')),
            ],
        ),
        migrations.AddField(
            model_name='chassis',
            name='io_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.iolist'),
        ),
        migrations.AddField(
            model_name='card',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.chassis'),
        ),
        migrations.CreateModel(
            name='BusDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IOList.device')),
                ('address', models.CharField(max_length=26)),
                ('tag', models.CharField(max_length=26)),
                ('description_1', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 1')),
                ('description_2', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 2')),
                ('description_3', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 3')),
                ('description_4', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 4')),
                ('io_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.iolist')),
            ],
            bases=('IOList.device',),
        ),
        migrations.AlterUniqueTogether(
            name='chassis',
            unique_together={('io_list', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('rack', 'slot')},
        ),
    ]
