# Generated by Django 3.2.9 on 2021-11-16 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IOList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvebank',
            name='address_template',
            field=models.CharField(blank=True, max_length=82, null=True),
        ),
        migrations.CreateModel(
            name='Solenoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('tag', models.CharField(max_length=26)),
                ('description_1', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 1')),
                ('description_2', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 2')),
                ('description_3', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 3')),
                ('description_4', models.CharField(blank=True, max_length=26, null=True, verbose_name='Desc 4')),
                ('user_address', models.CharField(blank=True, max_length=82, null=True, verbose_name='User Specified Address')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IOList.valvebank')),
            ],
        ),
    ]
