# Generated by Django 3.2.9 on 2021-12-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdevice',
            name='chassis',
            field=models.CharField(default='CP400d', max_length=20),
            preserve_default=False,
        ),
    ]
