# Generated by Django 3.2.9 on 2021-11-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOList', '0002_auto_20211116_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolist',
            name='controller',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Controller Name'),
        ),
        migrations.AlterField(
            model_name='iolist',
            name='name',
            field=models.CharField(max_length=82, verbose_name='IO List Name'),
        ),
        migrations.AlterField(
            model_name='valvebank',
            name='data_format',
            field=models.IntegerField(choices=[(4, 'SINT DATA'), (8, 'INT DATA')]),
        ),
        migrations.AlterUniqueTogether(
            name='busdevice',
            unique_together={('io_list', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('card', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='solenoid',
            unique_together={('bank', 'number')},
        ),
    ]
