# Generated by Django 3.2.9 on 2021-11-19 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IOList', '0003_auto_20211118_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='iolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iolist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IOList_Created_By', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='iolist',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='iolist',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IOList_Modified_By', to=settings.AUTH_USER_MODEL),
        ),
    ]
