# Generated by Django 3.2.9 on 2021-11-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IOList', '0004_auto_20211119_1928'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iolist',
            unique_together={('plant', 'name')},
        ),
    ]
